"""init

Revision ID: edb8b414119a
Revises: 
Create Date: 2026-01-05 09:09:58.204676

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb8b414119a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_location', sa.String(length=255), nullable=False),
    sa.Column('google_map_url', sa.String(length=512), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('invitation_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('response', sa.Enum('attending', 'not_attending', name='responsestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_responses')
    op.drop_table('users')
    op.drop_table('invitations')
    # ### end Alembic commands ###
